development:
  adapter: postgresql
  encoding: unicode
  database: district
  pool: 5
  username: sm
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: district
  pool: 5
  username: sm
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: district
  pool: 5
  username: sm
  password: 
